### ISSUE TITLE
Any way you could revive this project?

### ISSUE THREAD

**Issue by mateitudor** [Thomics/Pinterest-Screensaver#1]
Hello @Thomics,
I know Pinterest changed their API in a weird way and this probably won't work anymore but I was wondering if there's any way you'd consider working on this in the future.

I would love a Pinterest screensaver (for Mac). Would pay for it of course.

Thanks!

**Comment by Thomics** [comment]
I didn't actually know that Pinterest changed their API. I'll poke around with it tonight. The app in its current state is a bit rough around the edges but it worked the last I checked (a few months ago) so hopefully it won't be much work. I'll let you know what I find.

**Comment by Thomics** [comment]
Added a new domain, and pointed the site to it. Now we just have to wait a few hours for it to be functioning. I'll check on this tomorrow.

**Comment by mateitudor** [comment]
Hey, thank you for fixing this!
I'm taking the liberty to share two ideas with you. Feel free to disregard them if you want, they're not an imposition by any means.
- [ ] it would be nice to have the images in different customisation modes, like fill the screen, cover the screen with slow transitions if the image is too tall or too wide, or a masonry
- [ ] and the ability to shuffle the items or add all the boards

Thank you so much! You rock.

**Comment by mateitudor** [comment]
Hey, thank you for fixing this!
I'm taking the liberty to share two ideas with you. Feel free to disregard them if you want, they're not an imposition by any means.
- [ ] it would be nice to have the images in different customisation modes, like fill the screen, cover the screen with slow transitions if the image is too tall or too wide, or a masonry
- [ ] and the ability to shuffle the items or add all the boards

Thank you so much! You rock.

**Comment by gherson** [comment]
Hi, 
Before I attempt setup I have a related question.  These two links aren't working:
"You can view the app in it's old state at https://conto-pinterest.herokuapp.com/
You can view the MVP in it's current state at http://screensaver.netlify.com/"
Does that mean that the project code also likely won't work at present?  
Thank you.
